routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MachineController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserMachineTag;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::resource('/machine', MachineController::class);
Route::resource('/user', UserController::class);
Route::resource('/user-machine-tag', UserMachineTag::class);

Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
});

Route::get('/update-tag-status/{id}', [UserMachineTag::class, 'changeTagStatus'])->name('updateTagStatus');

app/Http/Controllers/UserMachineTag.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\machine;
use App\Models\User;
use App\Models\MachineUserTag;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

use Illuminate\Support\Facades\Auth;


class UserMachineTag extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $datas = DB::table('users')
            ->join('machine_user_tags', 'users.id', '=', 'machine_user_tags.user_id')
            ->join('machines', 'machines.id', '=', 'machine_user_tags.machine_id')
            ->select('machine_user_tags.hourly_session_charge', 'machine_user_tags.currency', 'machine_user_tags.id', 'machine_user_tags.is_taged', 'machine_user_tags.tagged_at', 'users.name', 'machines.machine_no')
            ->where(['is_taged' => 'Yes'])->get();



        return view('user-machine-tag.index', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $machines = DB::table('machine_user_tags')
            ->join('machines', 'machines.id', '=', 'machine_user_tags.machine_id')
            ->select('machines.machine_no', 'machines.id')
            ->where(['is_taged' => 'No'])->get();

        $users = User::all();

        return view('user-machine-tag.create', compact('machines', 'users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->machine_id);

        $inputs = $request->all();


        foreach ($inputs['machine_id'] as $key => $value) {
            $data = new MachineUserTag;
            $data->user_id = $request->user_id;
            $data->machine_id = $request->machine_id[$key];
            $data->hourly_session_charge = $request->hourly_session_charge;
            $data->currency = $request->currency;
            $data->tagged_at = Carbon::now()->addDays(30)->format('Y-m-d H:i:s');
            $data->tagged_by = Auth::id();
            $data->save();
            return Redirect()->route('user-machine-tag.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = MachineUserTag::find($id);
        return view('user-machine-tag.update', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'hourly_session_charge' => 'numeric',
        ]);

        $data = MachineUserTag::find($id);
        $data->hourly_session_charge = $request->hourly_session_charge;
        $data->save();
        return Redirect()->route('user-machine-tag.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function changeTagStatus($id)
    {
        $tag = MachineUserTag::find($id);

        MachineUserTag::where('id', $id)->update(['is_taged' => 'No']);
        return Redirect()->route('user-machine-tag.index');
    }
}

resources/views/user-machine-tag/create.blade.php
@extends('partials.master')
@section('content')

<form method="post" action="{{route('user-machine-tag.store')}}">
    @csrf
    <div class="form-group">
        <label >Select User</label>
        <select class="form-control" name="user_id">
        @foreach($users as $user)
            <option value="{{$user->id}}">{{$user->name}}</option>       
        @endforeach
        </select>
  </div>
  <div class="form-group">
    <label >Select Machine</label>
    <select multiple class="form-control" name="machine_id[]">
        @foreach($machines as $machine)
            <option value="{{$machine->id}}">{{$machine->machine_no}}</option>
        @endforeach
    </select>
  </div>

     <div class="form-group">
        <label for="exampleFormControlSelect1">Select Machine</label>
        <select class="form-control" id="exampleFormControlSelect1" name="currency">
            <option value="taka">Taka</option>
            <option value="doller">Doller</option>
            <option value="diner">Diner</option>
            <option value="pound">Pound</option>  
        </select>
  </div>

   <div class="form-group">
    <label for="exampleInputEmail1">Hourly Session Charge</label>
    <input name="hourly_session_charge" type="text" class="form-control">
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

@endsection

resources/views/user-machine-tag/index.blade.php
@extends('partials.master')
@section('content')


    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Admin Dashboard') }}
    </h2>

    <div class="mt-5" >
        <div class="row">
            <div class="col-3">

                <h3> Tag Machine </h3>

            </div>
            <div class="col-6"></div>
            <div class="col-3">

                <a class="btn btn-primary" href="{{route('user-machine-tag.create')}}">Tag Machine with User
                <!-- <i class="fa fa-user" aria-hidden="true"></i> -->
                </a>

            </div>
        </div>
    </div>

    <table class="table" >
        <thead>
            <tr>
            <th scope="col">User Name</th>
            <th scope="col">Machine Name</th>
            <th scope="col">Hourly Session Charge</th>
            <th scope="col">Tag Status</th>
            <th scope="col">Option</th>
            </tr>
        </thead>
        <tbody>
            @foreach($datas as $data)
                <tr>
                    <th>{{$data->name}}</th>
                    <td>{{$data->machine_no}}</td>
                    <td>{{$data->hourly_session_charge}}</td>
                    <td>{{$data->is_taged}}</td>
                    <td>
                        <a href="{{route('user-machine-tag.edit',$data->id)}}" class="btn btn-info">Edit</a> /
                        <a href="{{route('updateTagStatus', $data->id)}}" class="btn btn-info">Detag</a>
                        
                    </td>
                </tr>
            @endforeach    
        </tbody>
    </table>


@endsection

resources/views/user-machine-tag/update.blade.php
@extends('partials.master')
@section('content')



<div class="card" style="width: 100%">
  <div class="card-header">
    Update Session Rate
  </div>
  <ul class="list-group list-group-flush">
    <form method="post" action="{{route('user-machine-tag.update',$data->id)}}">
        @method('put')
        @csrf
        <div class="form-group">
            {{-- <label for="exampleInputEmail1">Hourly Session Charge</label> --}}
            <input name="hourly_session_charge" type="text" class="form-control" placeholder="Session Rate">
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </ul>
</div>

@endsection