routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MachineController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserMachineTag;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::resource('/machine', MachineController::class);
Route::resource('/user', UserController::class);
Route::resource('/user-machine-tag', UserMachineTag::class);

Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
});

Route::get('/update-tag-status/{id}', [UserMachineTag::class, 'changeTagStatus'])->name('updateTagStatus');

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin-dashboard.blade.php
@extends('partials.master')
@section('content')


    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Admin Dashboard') }}
    </h2>


    <div class="col-md-12 pt-2" >

        <div class="row">

            <div class="col-md-3 btn btn-secondary" style=" height:70px;width:100%;margin-left:auto;margin-right:auto">
            
                <a href="{{route('machine.index')}}" style="color:white; text-decoration:none;">
                    <h4 style="margin-top: 10px;">Machine Lists</h4>
                </a>
            
            </div>

            <div class="col-md-3 btn btn-success" style=" height:70px;width:100%;margin-left:auto;margin-right:auto">
            
                <a href="{{route('machine.create')}}" style="color:white; text-decoration:none">
                
                    <h4 style="margin-top: 10px;">Add Machine</h4>
                
                </a>
            
            </div>

            <div class="col-md-3 btn btn-info" style=" height:70px;width:100%;margin-left:auto;margin-right:auto">
            
                <a href="" style="color:white; text-decoration:none">
                    <h4 style="margin-top: 10px;">Invoice</h4>
                </a>
            
            </div>

        </div>

    </div>

    <div class="col-md-12 pt-2" >

        <div class="row">

            <div class="col-md-3 btn btn-secondary" style=" height:70px;width:100%;margin-left:auto;margin-right:auto">
            
                <a href="{{route('user.index')}}" style="color:white; text-decoration:none;">
                    <h4 style="margin-top: 10px;">Users List</h4>
                </a>
            
            </div>

            <div class="col-md-3 btn btn-success" style=" height:70px;width:100%;margin-left:auto;margin-right:auto">
            
                <a href="{{route('user.create')}}" style="color:white; text-decoration:none">
                
                    <h4 style="margin-top: 10px;">Add User</h4>
                
                </a>
            
            </div>

            <div class="col-md-3 btn btn-success" style=" height:70px;width:100%;margin-left:auto;margin-right:auto">
            
                <a href="{{route('user-machine-tag.index')}}" style="color:white; text-decoration:none">
                
                    <h4 style="margin-top: 10px;">Tag User Machine</h4>
                
                </a>
            
            </div>

            

        </div>

    </div>

@endsection

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user-dashbord.blade.php
@extends('partials.master')
@section('content')


    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('User Dashboard') }}
    </h2>

    <div class="card" style="width: 100%;">
        <div class="card-header">
            User Profile
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Name: {{$data->name}}</li>
            <li class="list-group-item">First Name: {{$data->first_name}}</li>
            <li class="list-group-item">Last Name: {{$data->last_name}}</li>
            <li class="list-group-item">Company Name: {{$data->company_name}}</li>
            <li class="list-group-item">Address: {{$data->address}}</li>
            <li class="list-group-item">Email: {{$data->email}}</li>
        </ul>
    </div>

@endsection