routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MachineController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserMachineTag;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::resource('/machine', MachineController::class);
Route::resource('/user', UserController::class);
Route::resource('/user-machine-tag', UserMachineTag::class);

Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
});

Route::get('/update-tag-status/{id}', [UserMachineTag::class, 'changeTagStatus'])->name('updateTagStatus');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function machines()
    {
        return $this->hasMany(machine::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datas = User::all();
        return view('users.index', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create_user');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = $this->validate($request, [
            'name' => 'required',
            'first_name' => 'required',
            'last_name' => 'required',
            'company_name' => 'required',
            'phone_number' => 'required|max:14',
            'address' => 'required',
            'tax_reg_no' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required',
        ]);



        $data = new User;
        $data->name = $request->name;
        $data->first_name = $request->first_name;
        $data->last_name = $request->last_name;
        $data->company_name = $request->company_name;
        $data->phone_number = $request->phone_number;
        $data->address = $request->address;
        $data->tax_reg_no = $request->tax_reg_no;
        $data->is_active = $request->is_active;
        $data->is_admin = $request->is_admin;
        $data->is_tagged = $request->is_tagged;
        $data->email = $request->email;
        $data->password = bcrypt($data->password);
        $data->save();
        return Redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $data = User::find($id);
        return view('users.update', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $validator = $this->validate($request, [
            'phone_number' => 'max:14',
        ]);



        $data =  User::find($id);
        $data->name = $request->name;
        $data->first_name = $request->first_name;
        $data->last_name = $request->last_name;
        $data->company_name = $request->company_name;
        $data->phone_number = $request->phone_number;
        $data->address = $request->address;
        $data->tax_reg_no = $request->tax_reg_no;
        $data->is_active = $request->is_active;
        $data->is_admin = $request->is_admin;
        $data->is_tagged = $request->is_tagged;
        $data->email = $request->email;
        $data->save();
        return Redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/create_user.blade.php
@extends('layout.master')
@section('content')

<div class="pt-5"><h3>User form<h3></div>

<form method="post" action="{{route('user.store')}}">
  @csrf
  <div class="mb-3">
    <label class="form-label">Name</label>
    <input type="text" name="name" class="form-control">
    @if ($errors->has('name'))

      <span class="text-danger">{{ $errors->first('name') }}</span>

    @endif
  </div>

  <div class="mb-3">
    <label class="form-label">First Name</label>
    <input type="text" name="first_name" class="form-control">
    @if ($errors->has('first_name'))

      <span class="text-danger">{{ $errors->first('first_name') }}</span>

    @endif
  </div>

  <div class="mb-3">
    <label class="form-label">Last Name</label>
    <input type="text" name="last_name" class="form-control">

    @if ($errors->has('last_name'))

      <span class="text-danger">{{ $errors->first('last_name') }}</span>

    @endif

  </div>

  <div class="mb-3">
    <label class="form-label">Company Name</label>
    <input type="text" name="company_name" class="form-control">
    @if ($errors->has('company_name'))

      <span class="text-danger">{{ $errors->first('company_name') }}</span>

    @endif
  </div>

  <div class="mb-3">
    <label class="form-label">Phone Number</label>
    <input type="number" name="phone_number" class="form-control">
    @if ($errors->has('phone_number'))

      <span class="text-danger">{{ $errors->first('phone_number') }}</span>

    @endif
  </div>

  <div class="mb-3">
    <label class="form-label">Address</label>
    <textarea rows="5" type="text" name="address" class="form-control"></textarea>
    @if ($errors->has('address'))

      <span class="text-danger">{{ $errors->first('address') }}</span>

    @endif
  </div>

  <div class="mb-3">
    <label class="form-label">Tax Registration Number</label>
    <input type="number" name="tax_reg_no" class="form-control">
    @if ($errors->has('tax_reg_no'))

      <span class="text-danger">{{ $errors->first('tax_reg_no') }}</span>

    @endif
  </div>

  <div class="mb-3">
      <label for="disabledSelect" class="form-label">Active / Deactive</label>
      <select name="is_active" class="form-select">
        <option value="no">No</option>
        <option value="yes">Yes</option>
      </select>
    </div>

    <div class="mb-3">
        <label for="disabledSelect" class="form-label">Admin option</label>
        <select name="is_admin" class="form-select">
          <option value="no">No</option>
          <option value="yes">Yes</option>
        </select>
      </div>

      <div class="mb-3">
          <label for="disabledSelect" class="form-label">Tag option</label>
          <select name="is_tagged" class="form-select">
            <option value="no">No</option>
            <option value="yes">Yes</option>
          </select>
        </div>

  <div class="mb-3">
    <label class="form-label">Email</label>
    <input type="email" name="email" class="form-control">
    @if ($errors->has('email'))

      <span class="text-danger">{{ $errors->first('email') }}</span>

    @endif
  </div>

  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input name="password" type="password" class="form-control" id="exampleInputPassword1">
    @if ($errors->has('password'))

      <span class="text-danger">{{ $errors->first('password') }}</span>

    @endif
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

@endsection

resources/views/users/index.blade.php
@extends('layout.master')
@section('content')

<div class="mt-5" >
  <div class="row">
      <div class="col-3">

        <h3>users Table</h3>

      </div>
      <div class="col-6"></div>
      <div class="col-3">

        <a class="btn btn-primary" href="{{route('user.create')}}">Add User
          <!-- <i class="fa fa-user" aria-hidden="true"></i> -->
        </a>

      </div>
  </div>
</div>

<table class="table" >
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Phone Number</th>
      <th scope="col">Company name</th>
      <th scope="col">Email</th>
      <th scope="col">Option</th>
    </tr>
  </thead>
  <tbody>
  @foreach($datas as $data)
      <tr>
        <th>{{$data->first_name}} {{$data->last_name}}</th>
        <td>{{$data->phone_number}}</td>
        <td>{{$data->company_name}}</td>
        <td>{{$data->email}}</td>
        <td>
          <a href="{{route('user.edit', $data->id)}}"  class="btn btn-primary" >Edit</a> /
          <a href="" class="btn btn-danger">Delete</a>
        </td>
      </tr>
  @endforeach
  </tbody>
</table>

@endsection

resources/views/users/update.blade.php
@extends('layout.master')
@section('content')

<div class="pt-5"><h3>Update User Data<h3></div>

<form method="post" action="{{route('user.update',$data->id)}}">
    @method('put')
  @csrf
  <div class="mb-3">
    <label class="form-label">Name</label>
    <input type="text" name="name" class="form-control" value="{{$data->name}}">
    @if ($errors->has('name'))

      <span class="text-danger">{{ $errors->first('name') }}</span>

    @endif
  </div>

  <div class="mb-3">
    <label class="form-label">First Name</label>
    <input type="text" name="first_name" class="form-control">
    @if ($errors->has('first_name'))

      <span class="text-danger">{{ $errors->first('first_name') }}</span>

    @endif
  </div>

  <div class="mb-3">
    <label class="form-label">Last Name</label>
    <input type="text" name="last_name" class="form-control">

    @if ($errors->has('last_name'))

      <span class="text-danger">{{ $errors->first('last_name') }}</span>

    @endif

  </div>

  <div class="mb-3">
    <label class="form-label">Company Name</label>
    <input type="text" name="company_name" class="form-control">
    @if ($errors->has('company_name'))

      <span class="text-danger">{{ $errors->first('company_name') }}</span>

    @endif
  </div>

  <div class="mb-3">
    <label class="form-label">Phone Number</label>
    <input type="number" name="phone_number" class="form-control">
    @if ($errors->has('phone_number'))

      <span class="text-danger">{{ $errors->first('phone_number') }}</span>

    @endif
  </div>

  <div class="mb-3">
    <label class="form-label">Address</label>
    <textarea rows="5" type="text" name="address" class="form-control"></textarea>
    @if ($errors->has('address'))

      <span class="text-danger">{{ $errors->first('address') }}</span>

    @endif
  </div>

  <div class="mb-3">
    <label class="form-label">Tax Registration Number</label>
    <input type="number" name="tax_reg_no" class="form-control">
    @if ($errors->has('tax_reg_no'))

      <span class="text-danger">{{ $errors->first('tax_reg_no') }}</span>

    @endif
  </div>

  <div class="mb-3">
      <label for="disabledSelect" class="form-label">Active / Deactive</label>
      <select name="is_active" class="form-select">
        <option value="no">No</option>
        <option value="yes">Yes</option>
      </select>
    </div>

    <div class="mb-3">
        <label for="disabledSelect" class="form-label">Admin option</label>
        <select name="is_admin" class="form-select">
          <option value="no">No</option>
          <option value="yes">Yes</option>
        </select>
      </div>

      <div class="mb-3">
          <label for="disabledSelect" class="form-label">Tag option</label>
          <select name="is_tagged" class="form-select">
            <option value="no">No</option>
            <option value="yes">Yes</option>
          </select>
        </div>

  <div class="mb-3">
    <label class="form-label">Email</label>
    <input type="email" name="email" class="form-control" value="{{$data->email}}">
    @if ($errors->has('email'))

      <span class="text-danger">{{ $errors->first('email') }}</span>

    @endif
  </div>

  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input name="password" type="password" class="form-control" id="exampleInputPassword1">
    @if ($errors->has('password'))

      <span class="text-danger">{{ $errors->first('password') }}</span>

    @endif
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

@endsection