routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MachineController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserMachineTag;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::resource('/machine', MachineController::class);
Route::resource('/user', UserController::class);
Route::resource('/user-machine-tag', UserMachineTag::class);

Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
});

Route::get('/update-tag-status/{id}', [UserMachineTag::class, 'changeTagStatus'])->name('updateTagStatus');

app/Models/machine.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class machine extends Model
{
    use HasFactory;

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/MachineController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\machine;

class MachineController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datas = machine::all();
        return view('machines.index', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('machines.create_machine');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'machine_no' => 'required|unique:machines'
        ]);
        $data = new machine;
        $data->machine_no = $request->machine_no;
        $data->is_active = $request->is_active;
        $data->is_delete = $request->is_delete;
        $data->is_tagged = $request->is_tagged;
        $data->save();
        return Redirect()->route('machine.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = machine::find($id);
        return view('machines.update', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'machine_no' => 'unique:machines'
        ]);
        $data = machine::find($id);
        $data->machine_no = $request->machine_no;
        $data->is_active = $request->is_active;
        $data->is_delete = $request->is_delete;
        $data->is_tagged = $request->is_tagged;
        $data->save();
        return Redirect()->route('machine.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/machines/create_machine.blade.php
@extends('layout.master')
@section('content')

<div class="pt-5"><h3>Machine form<h3></div>

<form method="post" action="{{route('machine.store')}}">
  @csrf
  <div class="mb-3">
    <label class="form-label">Machine No</label>
    <input type="text" name="machine_no" class="form-control">
    @if ($errors->has('machine_no'))

      <span class="text-danger">{{ $errors->first('machine_no') }}</span>

    @endif
  </div>

  <div class="mb-3">
    <label class="form-label">Active status</label>
    <select name="is_active" class="form-select">
      <option value="no">No</option>
      <option value="yes">Yes</option>
    </select>

  </div>
  <div class="mb-3">
    <label class="form-label">Delete status</label>
    <select name="is_delete" class="form-select">
      <option value="no">No</option>
      <option value="yes">Yes</option>
    </select>
  </div>

  <div class="mb-3">
    <label class="form-label">Tag status</label>
    <select name="is_tagged" class="form-select">
      <option value="no">No</option>
      <option value="yes">Yes</option>
    </select>

  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

@endsection

resources/views/machines/index.blade.php
@extends('layout.master')
@section('content')

<div class="mt-5" >
  <div class="row">
      <div class="col-3">

        <h3>Machinhe Table</h3>

      </div>
      <div class="col-6"></div>
      <div class="col-3">

        <a class="btn btn-primary" href="{{route('machine.create')}}">Add Machine
          <!-- <i class="fa fa-user" aria-hidden="true"></i> -->
        </a>

      </div>
  </div>
  <input type="search" onkeyup="search()" class="form-control" id="search" placeholder="search...">
</div>

<table class="table" >
  <thead>
    <tr>
      <th scope="col">Machine No</th>
      <th scope="col">Active Status</th>
      <th scope="col">Delete Status</th>
      <th scope="col">Tag Status</th>
      <th scope="col">Option</th>
    </tr>
  </thead>
  <tbody>
    @foreach($datas as $data)
      <tr>
        <th>{{$data->machine_no}}</th>
        <td>{{$data->is_active}}</td>
        <td>{{$data->is_delete}}</td>
        <td>{{$data->is_tagged}}</td>
        <td>
          <a href="{{route('machine.edit',$data->id)}}" class="btn btn-danger">Edit</a>
        </td>
      </tr>
    @endforeach
  </tbody>
</table>

<script>
  function search(){
    var search = $('#search').val();
    console.log(search);
  }
</script>

@endsection

resources/views/machines/update.blade.php
@extends('layout.master')
@section('content')

<div class="pt-5"><h3>Machine Update form<h3></div>

<form method="post" action="{{route('machine.update',$data->id)}}">
    @method('put')
  @csrf
  <div class="mb-3">
    <label class="form-label">Machine No</label>
    <input type="text" name="machine_no" class="form-control" value="{{$data->machine_no}}">
    @if ($errors->has('machine_no'))

      <span class="text-danger">{{ $errors->first('machine_no') }}</span>

    @endif
  </div>

  <div class="mb-3">
    <label class="form-label">Active status</label>
    <select name="is_active" class="form-select">
      <option value="no">No</option>
      <option value="yes">Yes</option>
    </select>

  </div>
  <div class="mb-3">
    <label class="form-label">Delete status</label>
    <select name="is_delete" class="form-select">
      <option value="no">No</option>
      <option value="yes">Yes</option>
    </select>
  </div>

  <div class="mb-3">
    <label class="form-label">Tag status</label>
    <select name="is_tagged" class="form-select">
      <option value="no">No</option>
      <option value="yes">Yes</option>
    </select>

  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

@endsection